#!/bin/sh
set -eu

output="${1:-lean/hypostructure_burgers1d_code.md}"
tmp="${output}.tmp"
files="$(mktemp)"

cleanup() {
  rm -f "$files" "$tmp"
}
trap cleanup EXIT

mkdir -p "$(dirname "$output")"

{
  if [ -f lean/lakefile.lean ]; then
    printf '%s\n' lean/lakefile.lean
  fi
  if [ -f lean/Hypostructure.lean ]; then
    printf '%s\n' lean/Hypostructure.lean
  fi
  find lean/Hypostructure -type f -name '*.lean' | sort
} | awk '!seen[$0]++' > "$files"

count="$(wc -l < "$files" | tr -d ' ')"

{
  printf '# Hypostructure Lean Code Bundle\n\n'
  printf 'This file is generated by `make code`.\n\n'
  printf 'It contains `lean/lakefile.lean`, `lean/Hypostructure.lean`, and every Lean file under `lean/Hypostructure/`, including the Burgers 1D backend and its Hypostructure literature dependencies.\n\n'
  printf 'File count: %s\n\n' "$count"

  printf '## Files\n\n'
  while IFS= read -r file; do
    printf -- '- `%s`\n' "$file"
  done < "$files"
  printf '\n'

  while IFS= read -r file; do
    printf '## `%s`\n\n' "$file"
    printf '````lean\n'
    cat "$file"
    printf '\n````\n\n'
  done < "$files"
} > "$tmp"

mv "$tmp" "$output"
printf 'Wrote %s with %s Lean files.\n' "$output" "$count"
